#!/bin/bash
# number of threads:
for t in 1 2 4 8 12 16
do
	echo NUMT = $t
	# number of subdivisions:
	for s in  5 10 50 100 250 500 1000 1250
	do
		echo NUMNODES = $s
		g++ -DNUMNODES=$s -DNUMT=$t project2.cpp -o prog -lm -fopenmp
		./prog >> project2data.txt
	done
    echo -e >> project2data.txt
done
